# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_auto_20170726_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='image',
            field=models.ImageField(default='../media/paymentimages/defaultpayment.png', upload_to='paymentimages'),
        ),
    ]
