# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_inquiry_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='image',
            new_name='paymentImage',
        ),
    ]
