# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0011_auto_20171212_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentImage', models.ImageField(default='../media/paymentimages/defaultpayment.png', upload_to='paymentimages')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Quotation')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentimages',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentimages',
            name='inquiry',
        ),
        migrations.RemoveField(
            model_name='paymentimages',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='paymentImages',
        ),
    ]
