# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_auto_20171212_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentimage',
            name='quotation',
        ),
    ]
