# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_auto_20171212_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentImage',
        ),
    ]
