# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0014_delete_paymentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentImage', models.ImageField(default='../media/paymentimages/defaultpayment.png', upload_to='paymentimages')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
