# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_paymentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentimage',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='paymentImage',
        ),
    ]
