# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_paymentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentimage',
            old_name='paymentImage',
            new_name='payment_image',
        ),
    ]
