# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_auto_20171214_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentimage',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental.Quotation'),
        ),
    ]
