# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
