# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-02 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0026_quotation_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
