# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0031_auto_20180403_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LR', 'Late_Return'), ('ER', 'Early_Return')], max_length=2)),
                ('status', models.CharField(choices=[('DM', 'Damaged'), ('WC', 'Working_Condition')], max_length=2)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Inquiry')),
            ],
        ),
    ]
