# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_total_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('IE', 'In Engagement'), ('AV', 'Available'), ('UM', 'Under Maintenance'), ('UR', 'Urgent Maintenance')], max_length=2),
        ),
    ]
