# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20180205_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('IE', 'In Engagement'), ('AV', 'Available'), ('UM', 'Under Maintenance'), ('UR', 'Urgent Maintenance'), ('RT', 'Retired')], max_length=2),
        ),
    ]
